### ISSUE TITLE
Разливная бочка не принимает зелья без эффекта

### ISSUE THREAD

**Issue by FaradeyYF** [feytox/Etherology#10]
Разливная бочка не принимает зелья без эффекта (обычную воду). Также из за того что зелье черепашьей мощи имеет два эффекта, пишет только первый, нужно что то сделать, может быть при наведении на бочку в инвентаре игроку покажут все эффекты, что содержит зелье, а если нажать по бочке в виде блока, то покажется название зелья.

**Comment by 1000fiv** [comment]
Теперь бочка принимает воду (раз раньше не принимала) и любое другое зелье без эффектов, но при нажатии по ней ПКМ или наведении курсора на неё в инвентаре (как я понял идёт попытка отобразить эффект) игра вылетает. Примечание: если я тут нафиг не нужен и вы сами прекрасно разберётесь, то только скажите - я пойму. Я не навязываюсь, да и баг нашёл случайно, пока знакомился с модом.

**Comment by feytox** [comment]
Теперь крашей не происходит, название пустого зелья заменяется на block.minecraft.water (т.е. Вода, Water и т.п.), а разные эффекты объединяются через &
![Image](https://github.com/user-attachments/assets/34c2cce7-4cc5-42de-b121-d773cf5fee7c)
